// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const backend = {
  "main": {
    "AppState": {
      /**
       * GetAppConfig
       * @returns {Promise<any>}  - Go Type: *models.AppConfig
       */
      "GetAppConfig": () => {
        return window.backend.main.AppState.GetAppConfig();
      },
      /**
       * GetEntryById
       * @param {any} arg1 - Go Type: models.GenericEntry
       * @returns {Promise<any>}  - Go Type: *models.GenericEntry
       */
      "GetEntryById": (arg1) => {
        return window.backend.main.AppState.GetEntryById(arg1);
      },
      /**
       * SelectDirectory
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "SelectDirectory": () => {
        return window.backend.main.AppState.SelectDirectory();
      },
    }
  }

};
export default backend;
